apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ros-ocp-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ros-ocp-backend
    app.kubernetes.io/part-of: ros-ocp-backend
  name: ros-ocp-backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ros-ocp-backend
status:
  loadBalancer: {}
